table TB_CONS_5902
	lineageTag: 067d576c-dc27-4fda-aef2-96960325bfee

	column Instalación
		dataType: int64
		formatString: 0
		lineageTag: 32974473-4189-4270-b456-b56717943377
		summarizeBy: sum
		sourceColumn: Instalación

		annotation SummarizationSetBy = Automatic

	column TOTAL
		dataType: double
		lineageTag: e2ef2fd5-2fb1-4372-8dc3-6ae0fca166ec
		summarizeBy: sum
		sourceColumn: TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoKIT
		dataType: string
		lineageTag: 9b0eac3b-9a1c-4a94-99e9-9b39cea99be4
		summarizeBy: none
		sourceColumn: TipoKIT

		annotation SummarizationSetBy = Automatic

	partition TB_CONS_5902 = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("D:\Descargas\VERISURE\archivos aparte\BASES DE DATOS.xlsx"), null, true),
				    TB_CONS_590_Table = Origen{[Item="TB_CONS_590",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(TB_CONS_590_Table,{{"Instalación", Int64.Type}, {"TOTAL", type number}, {"TipoKIT", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

